### ISSUE TITLE
Two entries for #5 in the website informations tab

### ISSUE THREAD

**Issue by dcollinsWhatever** [TunisianEagles/quasar#1]
I noticed that there are two #5 options in the website informations tab. Both Get Robots.txt and Host DNS Finder are assigned to #5 when you select #1 from the first menu. 

![temp](https://user-images.githubusercontent.com/42423127/47108588-e5adb680-d200-11e8-9ffc-d6e13c29c9f5.png)

**Comment by Cyb0r9** [comment]
thanks for reporting , it's Fixed Now
